# Generated by Django 5.1.6 on 2025-12-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
